# QR Factorisation

In this first part we will look at three different ways for computing the QR factorisation of a matrix. Remember that the goal is to start from a matrix $A$ and write it as the product of an orthogonal matrix $Q$ and an upper-triangular matrix $R$.

In [1]:
import numpy as np
import math
import numpy.linalg as npl
from numpy.linalg import norm

In [2]:
A = np.array([[1,2,3],[4,5,6],[7,8,10]])
n = 3

Numpy has a built-in function for doing this. Let's use it to check what the answer should be:

In [3]:
(Q,R) = npl.qr(A)
(Q,R)

(array([[-0.12309149,  0.90453403,  0.40824829],
        [-0.49236596,  0.30151134, -0.81649658],
        [-0.86164044, -0.30151134,  0.40824829]]),
 array([[ -8.1240384 ,  -9.6011363 , -11.93987462],
        [  0.        ,   0.90453403,   1.50755672],
        [  0.        ,   0.        ,   0.40824829]]))

## Gram-Schmidt orthogonalization

The first approach will be to transform the vectors in the columns of $A$ to a set of orthogonal vectores using the Gram-Schmidt approach. The basic idea of Gram-Schmidt is to build up an orthonormal set of vectors by projecting out non-orthogonal pieces. The following image illustrates this.
![Gram-Schmidt Visualisation](Gram-Schmidt_orthonormalization_process.gif "Gram-Schmidt Visualisation")
Let's now implement this with our test matrix $A$.

First, construct three vectors $a_1$, $a_2$ and $a_3$ from the columns of $A$.

In [ ]:
u1=a1, u2= a2- a2@u1/(u1@u1), u3=a3-a3@u2/(u2@u2)u2-a3@u1/(u1@u1)u1

In [43]:
x,y,z=A.T

In [44]:
print(x,y,z)

[1 4 7] [2 5 8] [ 3  6 10]


In [12]:
A[:,0]

array([1, 4, 7])

In [17]:
(a1, a2, a3) = A[:,0],A[:,1],A[:,2]

Now, our first orthonormal vector is just $a_1$ normalised to have length 1:

In [18]:
u1=a1

In [19]:
e1=u1/(np.sqrt(u1@u1))

To construct our second orthonormal vector, let's start with $a_2$, project out the part along the $a_1$ direction and normalise the result:

In [20]:
u2=a2- (a2@u1)/(u1@u1)*u1

In [21]:
e2=u2/(np.sqrt(u2@u2))

To construct our third orthonormal vector, let's project out the part along the previous two directions and normalise the result:

In [22]:
u3=a3- (a3@u2)/(u2@u2)*u2- (a3@u1)/(u1@u1)*u1

In [23]:
e3=u3/(np.sqrt(u3@u3))

Now we have our three orthogonal vectors, can put them into the columns of Q

In [24]:
print(e1,e2,e3)

[0.12309149 0.49236596 0.86164044] [ 0.90453403  0.30151134 -0.30151134] [ 0.40824829 -0.81649658  0.40824829]


In [27]:
Q = np.array([e1,e2,e3]).T

In [28]:
print(Q)

[[ 0.12309149  0.90453403  0.40824829]
 [ 0.49236596  0.30151134 -0.81649658]
 [ 0.86164044 -0.30151134  0.40824829]]


To get $R$, we note that $A = Q R$ means that $Q^T A = Q^T Q R = R$ since $Q$ is an orthogonal matrix. Let's use this to compute $R$:

In [38]:
R = Q.T@A

In [39]:
Q

array([[ 0.12309149,  0.90453403,  0.40824829],
       [ 0.49236596,  0.30151134, -0.81649658],
       [ 0.86164044, -0.30151134,  0.40824829]])

In [40]:
R

array([[ 8.12403840e+00,  9.60113630e+00,  1.19398746e+01],
       [-6.49480469e-15,  9.04534034e-01,  1.50755672e+00],
       [ 9.15933995e-15,  3.10862447e-14,  4.08248290e-01]])

As expected, $R$ is (almost) an upper-triangular matrix. It is only __almost__ upper triangular because floating point arithmetic is not exact.